# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-17 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='商品名称', max_length=100, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=1000, null=True, verbose_name='描述')),
                ('goods_images', models.CharField(default='[]', max_length=1000, verbose_name='商品图列表')),
                ('detail_images', models.CharField(default='[]', max_length=1000, verbose_name='商品详情图列表')),
                ('spec_name', models.CharField(default='规格', max_length=20, verbose_name='规格名称')),
                ('is_saller_empower', models.BooleanField(default=False, verbose_name='卖家上架')),
                ('is_admin_empower', models.BooleanField(default=False, verbose_name='管理员上架审批')),
                ('is_delete', models.BooleanField(default=False, verbose_name='商品无效')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='此规格的价格')),
                ('spec_info', models.CharField(max_length=100, verbose_name='规格信息')),
                ('stock', models.IntegerField(default=1, verbose_name='库存')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='分类名称', max_length=30, verbose_name='分类名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否下架')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType'),
        ),
    ]
